version: '3.8'

networks:
  myNetwork:
    driver: bridge

services:

  zookeeper:
    image: bitnamilegacy/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - myNetwork

  kafka:
    image: bitnamilegacy/kafka:3.7
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ENABLE_KRAFT: "no"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - myNetwork

  starrocks:
    image: starrocks/allin1-ubuntu:3.2.8
    container_name: starrocks
    ports:
      - "8030:8030"
      - "9030:9030"
      - "8040:8040"
      - "9020:9020"
    networks:
      - myNetwork

  vector:
    image: timberio/vector:0.37.0-alpine
    depends_on:
      - kafka
      - starrocks
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
    networks:
      - myNetwork